source 'https://rubygems.org'

gem 'rake'

# style
gem 'foodcritic'
gem 'rubocop', require: false

# unit
gem 'rspec'
gem 'chefspec'
gem 'berkshelf'

# integration
gem 'serverspec'
gem 'test-kitchen'
